export enum CartActionTypes {
  ADD_TO_CART = 'ADD_TO_CART',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  UPDATE_PAYMENT_TYPE = 'UPDATE_PAYMENT_TYPE',
  UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY',
}
